vim.defer_fn(function()
    vim.fn.execute("e src/bf_game_screen.cpp")
    vim.api.nvim_input([[<space>n<C-j><C-j>]])
    vim.defer_fn(function()
        vim.api.nvim_input([[<C-j><C-j><A-m><A-q><A-m>]])
    end, 600)
end, 1)
