// #define BF_ENABLE_FRAMESKIPPING (0 || BF_RELEASE)
// #define BF_ENABLE_FRAMESKIPPING (0)

// #define BF_ENABLE_LOGGING (1 && BF_DEBUG)
// #define BF_USE_TRACING_LOGGER 0

#define BF_ENABLE_ASSERTS (1 && BF_DEBUG)
#define BF_ENABLE_SLOW_ASSERTS (1 && BF_ENABLE_ASSERTS)

// #define BF_ENABLE_SANITIZATION (0 && BF_DEBUG)
//
// #define BF_FORCE_GIZMOS_ENABLE (0 && BF_DEBUG)
//
// // #define BF_MIN_REPLAYING_SIMULATION_FRAMES 1
// #define BF_MIN_REPLAYING_SIMULATION_FRAMES 100
//
// #define BF_FAST_REPLAY_UP_TO_RELOADED_COUNT (-1)
// // #define BF_FAST_REPLAY_UP_TO 300
// #define BF_FAST_REPLAY_UP_TO int_max
//
// #define BF_VALIDATE_REPLAY 1
// #define BF_INPUTS_HANDLING_TYPE_DEBUG InputsHandlingType_REPLAYING
// #define BF_INPUTS_HANDLING_TYPE_RELEASE InputsHandlingType_RECORDING
